apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets
      service: web
      color: green
  template:
    metadata:
      labels:
        app: pets
        service: web
        color: green
    spec:
      containers:
      - image: appswithdockerandkubernetes/ch11-web:2.0
        name: web
        ports:
        - containerPort: 3000
          protocol: TCP
