apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets
      service: web
      color: blue
  template:
    metadata:
      labels:
        app: pets
        service: web
        color: blue
    spec:
      containers:
      - image: appswithdockerandkubernetes/ch08-web:1.0
        name: web
        ports:
        - containerPort: 3000
          protocol: TCP
